### PR TITLE
Fix page content indicators on tables

### LINKED ISSUE #607: Page content indicators are misleading
Take any EHR page that has a table that does not yet have data. The navigation menu does not have any green circle indicator.

Add a row of data.
Clear the table of all data with the "clear all data" button.

Note how the indicator is still present.  This is because the database has an empty array [] for this page.

Fix the algorithm that computes if data is present to account for empty arrays.

### PR DESCRIPTION
**Pull request by viniciusarre**
Closes #607

### CODE REVIEW

File: client/src/store/modules/ehrDataStore.js [hunk 1]
```diff
@@ -46,10 +46,18 @@ const getters = {
     const studentData = rootGetters['activityDataStore/assignmentData'] || {}
     let results = {}
     pageKeys.forEach( key => { 
+      const combinedObject = Object.assign({}, mergedData[key], seedData[key])
+      const isTable = Object.keys(combinedObject).includes('table')
```
Comment (bryan-gilbert) [inline client/src/store/modules/ehrDataStore.js]: Is this check for 'table' fragile?  Might the work 'table' appear in the data?  Can you find a more robust way to detect the page has *one or more* tables.

Comment (viniciusarre) [reply client/src/store/modules/ehrDataStore.js]: @bryan-gilbert, I have implemented it in a new way. I have divided into three main groups (1. It has one or more tables; 2. Has one or more tables and other content; 3. Has no tables). I have implemented it in a way that, it identifies which use cases it would fall into and implement a different logic for each. I think it improves the overall logic when it comes to the issues commented... I look forward to your thoughts on it. Thank you!
